input_boolean:
  theme_override:
    name: Override Theme
    icon: mdi:toggle-switch

  dark_theme: 
    name: Dark Theme 
    icon: mdi:theme-light-dark


frontend:
  themes:
    day:
      primary-color: "#03a9f4"
      background-color: "#ffffff"
      primary-background-color: "#ffffff"
      card-background-color: "#ffffff"
      text-color: "#000000"
      primary-text-color: "#000000"
    night:
      primary-color: "#03a9f4"
      background-color: "#000000"
      primary-background-color: "#121212"
      card-background-color: "#1e1e1e"
      text-color: "#ffffff"
      primary-text-color: "#ffffff"
      secondary-text-color: "#cccccc"
      app-header-background-color: "#1e1e1e"
      app-header-text-color: "#ffffff"
      code-editor-text-color: "#ffffff"
      accent-color: "#03a9f4"
      divider-color: "#444444"
      input-text-color: "#ffffff"
      input-disabled-text-color: "#666666"    
      secondary-background-color: "#1c1c1c"
      code-editor-background-color: "#1c1c1c"
      switch-unchecked-button-color: '#777777'
      switch-unchecked-track-color: '#505050'
      switch-checked-button-color: "#1e88e5"
      switch-checked-track-color: "#64b5f6"
      input-background-color: "#1e1e1e"
      input-fill-color: "#1e1e1e"
      input-ink-color: "#ffffff"
      input-label-ink-color: "#aaaaaa"
  